<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbf471a1fb2b3082ce10cf5f1f90f948f
{
    public static $prefixLengthsPsr4 = array (
        'Q' => 
        array (
            'Qiwi\\Api\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Qiwi\\Api\\' => 
        array (
            0 => __DIR__ . '/..' . '/qiwi/bill-payments-php-sdk/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'C' => 
        array (
            'Curl' => 
            array (
                0 => __DIR__ . '/..' . '/curl/curl/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbf471a1fb2b3082ce10cf5f1f90f948f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbf471a1fb2b3082ce10cf5f1f90f948f::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitbf471a1fb2b3082ce10cf5f1f90f948f::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
